
#ifndef _ALARM_CLASS_
#define _ALARM_CLASS_

enum AlarmStatus {
					ALARM_ENDED,	//0
					ALARM_STARTED,	//1
					ALARM_REPORTED,	//2
					ALARM_ACK,		//3					

};

enum ReamStatus{
					REMA_NONE,		//0
					REMA_SEND,		//1
					REMA_REPORT,	//2
};

//GetDetails flags
#define GET_DETAILS_CATEGORY		0x00001	
#define GET_DETAILS_SUB_CATEGORY	0x00002	


// AlarmSrv Event flags
#define ALARM_EVENT_INFORM_ON_NEXT_ALARM      0x000001  // This event inform on update next exist alarm to delete group



#define CONFIGURATION_XML_FILE_NAME		"C:\\Program Files\\Retalix\\AlarmSrv\\AlarmSrv.xml"
#define CONFIGURATION_PATH_NAME			"C:\\Program Files\\Retalix\\AlarmSrv"
#define XML_FILES_PATH					"C:\\Program Files\\Retalix\\AlarmSrv\\Alarms"

// DataBase type 
#define DATA_BASE_INI_FILE		 0
#define DATA_BASE_XML_FILE		 1

// 1.0.0.30
#define FILE_CONFIGURATION_INI   "\\AlarmCfg.ini"
#define FILE_CONFIGURATION_XML   "\\AlarmCfg.xml"

#define FILE_ALARMSRV_RUNTIME_INI  "\\AlarmSrvRunTimeFile.ini"

// fields size
#define MAX_DESC_LEN				100    //1.0.0.13
#define MAX_APPLICATION_IDENTIFIER  50 

#define MAX_ALARM_DESC_LEN          MAX_DESC_LEN 
#define MAX_ALARM_ID				12
#define MAX_SERVER_NAME				100
#define	MAX_TABLE_NAME				100
#define MAX_PATH_NAME				MAX_SERVER_NAME+MAX_TABLE_NAME
#define MAX_REC_VALUES				1000


#define MAX_CATEGORY_DESCRIPTION	50

// Alarm end type
#define ALARM_END_TYPE_BY_OK		0
#define ALARM_END_TYPE_BY_TIME_OUT	1
#define ALARM_END_TYPE_BY_ACK		2

//Flags for the GAI::GetAlarm(...) methode.
#define ALL_ALARMS		0x0000
#define	FIRST_ALARM		0x0001
#define	NEXT_ALARM		0x0002

//Alarm status
#define ALARM_OFF		0
#define ALARM_ON		1
#define ALARM_DELETE	2
#define ALARM_ACK		3


// sort type.
#define IGNORE_CATEGORY_NUMBER			0
#define IGNORE_SUB_CATEGORY_NUMBER		0
#define IGNORE_DEVICE_NUMBER			0
#define IGNORE_ALARM_NUMBER				0


// retrieve data flags
#define GET_DIRECT_INDEX	1 
#define GET_FIRST_INDEX		2 
#define GET_NEXT_INDEX		3 

// Alarm types
#define ALARM_TYPE_UNDEFINE	0
#define ALARM_TYPE_WARNING	1
#define ALARM_TYPE_ERROR	2
#define ALARM_TYPE_MISC		3  


// Get Alarm by Category flags. 
#define GABC_ONLY_DISPLAY_MESSAGES						0x00000001
#define GABC_WITHOUT_SOFTWARE_GENERAL_OLA_ERR			0x00000002		//1.0.20.0


#define MAINTENANCE_PROCESS_TIME_OUT			1800 //(half hour  * 1000)
#define MAINTENANCE_XML_SAMPLE_FACTOR			60000

enum GAIRetCode {

			GAI_OK,							// 0
			GAI_INVALID_CATEGORY_NUMBER,	// 1
			GAI_INVALID_SUBCATEGORY_NUMBER,	// 2
			GAI_INVALID_ALARM_NUMBER,		// 3
			GAI_INVALID_DEVICE_NUMBER,		// 4
			GAI_INVALID_ALARM_STATUS,		// 5
			GAI_ALARM_NOT_FOUND,			// 6
			GAI_INVALID_PARAMETER,			// 7
			
				
};

enum AlarmSrvCtrlRetCode
{
	ALARMSRV_CTRL_OK = 0,
	ALARMSRV_CTRL_FAILED_TO_OPEN_TABLE,
	ALARMSRV_CTRL_PARAM_NOT_FOUND,
	ALARMSRV_CTRL_TABLE_NAME_TOO_LONG,
	ALARMSRV_CTRL_FIELD_NAME_TOO_LONG,
	ALARMSRV_CTRL_DEFAULT_FIELD_VAL_TOO_LONG,
	ALARMSRV_CTRL_LAST_ERROR,
	ALARMSRV_CTRL_CATEGORY_NOT_VALID,
	ALARMSRV_CTRL_SUB_CATEGORY_NOT_VALID,	
};
	
enum MailSrvStatusSend
{
    MAIL_SEND_ALWAYS,        //0
	MAIL_SEND_ON_CREATE,     //1
	MAIL_SEND_ON_DELETE,     //2
};

//1.0.13.500
enum CreateXmlOnStatus {
	XML_ON_CREATE_AND_DELETE, //0
	XML_ON_CREATE,			  //1
	XML_ON_DELETE,			  //2
};

//1.0.22.0 - TD 70576
enum EventSendStatus {
	EVENT_SEND_ON_CREATE_AND_DELETE,  //0
	EVENT_SEND_ON_CREATE,			  //1
	EVENT_SEND_ON_DELETE,			  //2
};

#pragma pack(1)


typedef struct
{
	BYTE  sCategoryID[2];
	BYTE  sCategoryDes[MAX_CATEGORY_DESCRIPTION]; 
}CATEGORY_DETAILS;


typedef  struct
{
	BYTE	sCaterory[2];
	BYTE	sSubCaterory[2];  
	BYTE	sAlarmNumber[3];  //4.0.8.500
 	BYTE	sDevice[3];       //4.0.8.500
	BYTE	sStatus[2];
	BYTE	sDescription[MAX_DESC_LEN];
	BYTE	sAlarmId[11];
	BYTE	sAlarmType[2];
	BYTE	sRightAlignment[2];
	BYTE	sAlarmPriority[2];  //1.0.0.13
	BYTE	sAlarmEndType[2];
	BYTE	sShowAckUI[2];		//1.0.15.500 - CR 34668
	BYTE	sSendToWMI[2];		//1.0.19.500 (TD 60465)
	BYTE	sSendToEventViewer[2]; //1.0.22.0 - TD 70576
	BYTE    sFiler[72];			//1.0.22.0 - TD 70576
	//BYTE    sFiler[74];		//1.0.19.500 (TD 60465)
	//BYTE    sFiler[76];	
	//BYTE    sFiler[78];		//1.0.15.500
	//BYTE    sFiler[80];		//1.0.9.500	
} ALARM_CATEGORY_INFO;

typedef  struct
{
	DWORD	m_lAlarmId;								// 0 - 3
	SYSTEMTIME m_cUpdateTime;						// 4 - 19	
	SYSTEMTIME m_cStartTime;						//20 - 35
	SYSTEMTIME m_cCurrStateTime;					//36 - 51	
	LONG	m_lAlarmCategory;						//52 - 55
	LONG	m_lAlarmSubCategory;					//56 - 59
	LONG	m_lAlarmNumber;							//60 - 63
	LONG	m_lDeviceNumber;						//64 - 67
	LONG	m_lState ;								//68 - 71
	LONG	m_lAlarmPriority;						//72 - 75
	BYTE	m_szAlarmDescription[MAX_DESC_LEN];		//76 - 175
	BOOL	m_bSendToREMA;							//176- 179  
	BOOL	m_bSendToClient;						//180- 183
	LONG	m_lAlarmEndedType;						//184- 187 
	LONG	m_lAlarmTimeOut;						//188- 191
	LONG	m_lAlarmType;							//192- 195
	LONG	m_lMatrixMemberId;						//196- 199
	LONG	m_lStoreInternalId;						//200- 203	
	LONG	m_lRemaComponentId;						//204- 207			
	LONG	m_lRemaAlertId;							//208- 211
	BYTE	m_szApplicationIdentifier[MAX_DESC_LEN];//212- 311
	BOOL	m_bCreateXMLFile;						//312- 315	1.0.0.12
	BOOL	m_bSaveToDataBase;						//316- 319
	BOOL	m_bRightAlignment;						//320- 323
	LONG	m_lAlarmValue;							//324- 327	
	LONG	m_lSendEmailToGroup;					//328- 331	 //1.0.0.22	
	LONG	m_lSendEmailOnStatus;					//332 - 335 1.0.0.26
	LONG	m_lSeqNumber;							//336 - 339	
	BOOL	m_bAddToTextFile;						//340- 343	
	LONG	m_lDistributionTimeout;					//344- 347 //1.0.12.60
	BOOL	m_bSendToMSMQ;							//348- 351 //1.0.12.501		
	BOOL	m_bIsDistributed;						//352- 355
	LONG	m_lCreateXmlOnStatus;					//356- 359 //1.0.13.500
	BOOL	m_bDoNotCreateXmlFileOnAck;				//360- 363  //1.0.15.500 - CR 34668
	BOOL	m_bShowAckUI;							//364- 367  //1.0.15.500 - CR 34668	
	BOOL	m_bSendToWMI;							//368- 371	//1.0.19.500 (TD 60465)
	BOOL	m_bSendToEventViewer;					//372- 375	//1.0.22.0 - TD 70576
	LONG	m_lSendToEventViewerOnStatus;			//376- 379	//1.0.22.0 - TD 70576
	LONG	m_lEventViewerId;						//380- 383	//1.0.22.0 - TD 70576
	BOOL	m_bAddMachineAliasNameToFileName;		//384- 387	//4.0.24.90
	LONG	m_lMaxAlarmCounter;						//388- 391	//TD 162766
	LONG	m_lSnoozeInterval;  					//388- 391  // 1.0.28.501 - TD 123988
	LONG	m_lSnoozeAttempts;  					//392- 395  // 1.0.28.501 - TD 123988  
	BYTE	spare[110];								//388- 510	// 1.0.28.501 - TD 123988 
	
	//BYTE	spare[143];								//371- 510	//1.0.19.500 (TD 60465)
	//BYTE	spare[147];								//368- 510	 //1.0.12.501
	//BYTE	spare[171];								//344- 347	 //1.0.0,22  //1.0.0.26
	//BYTE	spare[175];								//336- 339	 //1.0.0,22  //1.0.0.26
	//BYTE	spare[265];								//- 510	 //1.0.0,22
	//BYTE	spare[315];								//196- 510	 //1.0.0.22
	//BYTE	spare[319];								//191- 510	
}ALARM_INFO_DATA;

typedef struct 
{	
	ALARM_INFO_DATA		 info;	
	BYTE			byQdexFlg;
}ALARM_SRV_REC;


#pragma pack()

//typedef struct {
//	CATEGORY_INFO   CategoryInfo[x];
//} TAG_CATEGORY_ALARM;

/***********************************************
 This section Defines the alarms in the System 
************************************************/

/****************************
   Alarms Categories
*****************************/
#define CATEGORY_UNKNOWN	0
#define CATEGORY_TANK		1
#define CATEGORY_PUMP		2
#define CATEGORY_SOFTWARE	3
#define CATEGORY_DEVICES	4
#define CATEGORY_CONTROLLER 5 
#define CATEGORY_ONLINE_SERVICES		    6

#define CATEGORY_STOREPOINT_BOS_OFFICE      7
#define CATEGORY_STOREPOINT_OFFICE_SERVICES 8
#define CATEGORY_STOREPOINT_POS				9

#define CATEGORY_STORELINE_FO				20   
#define CATEGORY_STORELINE_POS				21
#define CATEGORY_STORELINE_SYSTEM			22
#define CATEGORY_STORELINE_CDS				23
#define CATEGORY_STORELINE_INTERFACES		24



/****************************
  Alarms SubCategories
*****************************/
#define SUB_UNKNOWN			0

//CATEGORY_TANK
#define SUB_TANK_GAUGE		1
#define SUB_TANKS			2

//CATEGORY_PUMP
#define SUB_TERMINAL				1	
#define SUB_TERMINAL_CARD_READER	2
#define SUB_TERMINAL_PRINTER		3
#define SUB_TERMINAL_KEYBOARD		4
#define SUB_TERMINAL_DISPLAY		5
#define SUB_TERMINAL_SPEAKER		6
#define SUB_TERMINAL_CASH_ACCEPTOR	7
#define SUB_TERMINAL_DISPENSER		8 
#define SUB_TERMINAL_RFID_ANTENNA	9
#define SUB_TERMINAL_ENCRYPTION		10
#define SUB_PRICE_CHANGE			11		//1.0.8.501
#define SUB_SCANNER					12      //1.0.15.0
#define SUB_ANPR					13      //TD 147049


//CATEGORY_SOFTWARE
#define SUB_PUMPSRV				1	
#define SUB_CL2PUMPSRV			2
#define SUB_TANKSRV				3
#define SUB_GENERATOR			4
#define SUB_BUYATPUMP			5
#define SUB_MULTI_SYNC			6
#define SUB_QDX					7  //1.0.0.19
#define SUB_ATS					8 
#define SUB_FUEL_MAINT			9
#define SUB_OLA					10 //4.0.21.0
#define SUB_FCC					11 //4.0.21.0 
#define SUB_ALARMSRV			12
#define SUB_DATABASE			13

//CATEGORY_DEVICES
#define SUB_CAR_WASH			1
#define SUB_FUEL_ADDITIVE		2
#define SUB_ENCRYPTION			3
#define SUB_IPT					4
#define SUB_AVI					5
#define SUB_PRICE_POLE			6
#define SUB_ITL					7
#define SUB_CHIP_AND_PIN		8 
#define	SUB_UPS					9
#define	SUB_DEVICE_ANPR			10 //TD 157073 


// CATEGORY_CONTROLLER
#define SUB_MEGGIT				1
#define SUB_ALLIED				2
#define SUB_RFS					3
#define SUB_POSTEC				4  //1.0.16.10
#define SUB_DOMS				5  
#define SUB_GENERAL				6  //2.0.17.500 //4.0.21.0
#define SUB_WAYNE				7 
#define SUB_HTEC                8  //4.0.27.500 


// CATEGORY ONLINE SERVICES
#define SUB_PAYMENT_NETWORK				1
#define SUB_EMV							2

/*****************************************
				Alarms Numbers
*****************************************/
#define UNSPECIFIC_ALARM				0


/******************************************
	TANKS ALARMS		
*******************************************/
//Tanks Gauge Alarms
#define PRINTER_OUT_OF_PAPER			1
#define PRINTER_ERR						2
#define EEPROM_CONFIG_ERR				3
#define BATTERY_OFF						4
#define TOO_MANY_TANKS					5
#define SYSTEM_SECURITY_WARNING			6
#define ROM_REVISION_WARNING			7
#define REMOTE_DISPLAY_COMM_ERR			8
#define AUTODIAL_ERR					9
#define SOFTWARE_MODULE_WARNING			10
#define TANK_TEST_SHUTDOWN_WARNING		11
#define PROTECTIVE_COVER_ALARM			12
#define BIR_SHIFT_CLOSE_PENDING			13
#define BIR_DAILY_CLOSE_PENDING			14
#define PC_H8_REVISION_WARNING			15
#define SYSTEM_SELF_TEST_WARNING		16
#define SYSTEM_CLOCK_INCORRECT_WARNING	17
#define SYSTEM_DEVICE_POLL_TIMEOUT		18
#define TANK_GAUGE_NOT_AVAILABLE		19
#define ATG_SENSORS_PROBLEM				20
#define ATG_ERROR_RESPONSE				21
#define ATG_GENERIC_ALARM				22


//Tanks Alarms
#define TANK_ALARM_OK					0
#define SETUP_DATA_WARNING				1
#define LEAK_ALARM						2
#define HIGH_WATER_ALARM				3
#define OVERFILL_ALARM					4
#define LOW_PRODUCT_ALARM				5
#define SUDDEN_LOSS_ALARM				6
#define HIGH_PRODUCT_ALARM				7
#define INVALID_FUEL_LEVEL_ALARM		8
#define PROBE_OUT_ALARM					9
#define HIGH_WATER_WARNING				10
#define DELIVERY_NEEDED_WARNING			11
#define MAXIMUM_PRODUCT_ALARM			12
#define GROSS_LEAK_TEST_FAIL_ALARM		13
#define PERIODIC_LEAK_TEST_FAIL_ALARM	14
#define ANNUAL_LEAK_TEST_FAIL_ALARM		15
#define PERIODIC_TEST_WARNING			16
#define ANNUAL_TEST_WARNING				17
#define PERIODIC_TEST_ALARM				18
#define ANNUAL_TEST_ALARM				19
#define LEAK_TEST_ACTIVE				20
#define NO_CSLD_IDLE_TIME_WARNING		21
#define SIPHON_BREAK_ACTIVE_WARNING		22
#define CSLD_RATE_INCREASE_WARNING		23
#define ACCU_CHART_CALIBRATION_WARNING	24
#define HRM_RECONCILIATION_WARNING		25
#define HRM_RECONCILIATION_ALARM		26
#define COLD_TEMPERATURE_WARNING		27
#define MISSING_DELIVERY_TICKET_WARNING	28
#define TANK_NOT_AVAILABLE				29
#define TANK_DELIVERY_IN_PROGRESS		30
#define TANK_DELIVERY_ENDED				31
#define TANK_LEAKAGE					32 //4.0.13.501
#define TANK_EXTRA						33 //4.0.13.501
#define TANK_INVALID_WATER_LEVEL_ALARM  34 //4.0.13.508
#define TANK_INVALID_FUEL_VOLUME_ALARM  35 //4.0.13.508
#define TANK_MIN_VOLUME_WARNING         36 //4.0.25.690


#define MAX_ALARM_PER_CATAGORY			40	   // veeder Root Standard

#define WET_STOCK_TIMEOUT				300



/******************************************
	PUMPS ALARMS		
*******************************************/
//General Pump Alarm(Cat 2, Subcat 0)
//#define PUMP_OUT_OF_SERVICE			 1


//Pumps Dispenser Alarms(Cat 2, Subcat 8)
#define DISPENSER_ERROR_NOT_SPECIFIC		1
//#define DISP_OFFLINE_WARNING				2
#define BLENDER_ERR							3
#define CONFIGURATION_ERR					4
#define DISPENSER_OVER_FUELLING				5				
#define DISPENSER_ILLEGAL_GRADE_PRICE		6
#define PUMP_OUT_OF_SERVICE					7
#define POSTEC_PAP_TRANS_MOVE_TO_MEMORY_BUFFER 8
#define WRONG_SECURITY_CODE_IN_MODE			9
#define TEMPORARY_MEMORY_ERROR				10
#define LOW_BACKUP_BATTERY_VOLTAGE_STILL_ENOUGH 11
#define LOW_BACKUP_BATTERY_VOLTAGE_OR_UNPLUGGED 12
#define TO_MANY_PULSER_ERRORS_IN_MODE_21	13
#define TO_MANY_TRS_WITH_PUL_ERRORS_IN_MODE_21	14
#define DISPENSER_OFFLINE_WARNING			20 
#define DISPENSER_GENERIC_ALARM				21
#define MORE_THAN_ONE_NOZZLE_OUT			22
#define ELECTROMECHANICAL_TOTALIZER_ERRRO	23
#define NOZZLE_OUT_ON_POWER_UP				24
#define DISPENSER_DISPLAY_ERROR				25
#define SW_VERSION_VALIDATION_ERROR			26
#define ERROR_IN_PULSE_GENERATOR			27
#define ERROR_IN_GLOBAL_TOTALS				28
#define GRADE_NOT_CONFIGURED				29
#define PRICE__LEVEL_NOT_CONFIGURED			30
#define COMMUNICATION_ERROR					31
#define DISPENSER_UNEXPECTED_PUMP_START     32  //old
#define DISPENSER_TRANS_DATA_ERROR          33  //old
#define POWER_FAIL_OR_LOW_SUPPLY_VOLTAGE	34
#define CORRUPTED_CONFIG_RECOVERABLE		35
#define CORRUPTED_CONFIG_NOT_RECOVERABLE	36
#define VAPOR_RECOVERY_ENABLED_NO_RESPONSE  37
#define VAPOR_RECOVERY_COUNTDOWN_ACTIVATED  38
#define VAPOR_RECOVERY_COUNTDOWN_LIMIT_REACHED  39
#define CONVERSION_FACTOR_ERROR					40 // 2.5.30.0 CR 274735
#define PUMP_NOT_CALIBRATED						41 // 2.5.30.0 CR 274735
#define PUMP_TIMOUT								42 // 2.5.30.0 CR 274735
#define ADBLUE_FREZZE_ERROR						43 // 2.5.30.0 CR 274735
#define MAXIMUM_AUTH_TIME						44 // 2.5.30.0 CR 274735
#define STOP_BUTTON_ACTIVATED					45 // 2.5.30.0 CR 274735
#define PUMP_HANDLE_ERROR						46 // 2.5.30.0 CR 274735
#define MINIMUM_PRESET_ERROR					47 // 2.5.30.0 CR 274735
#define GENERAL_GRADE_ERROR						48 // 2.5.30.0 CR 274735
#define DISPENSER_BATTERY_ERROR					49
// define Reset Pump Failed
#define CARD_SWIPED_DURING_PAK					51 // CR 404902
#define PAP_AUTHORIZE_TIMEOUT					52 // CR 404823


//special function 603 codes:	//CR 465678:
#define RAM_DATABASE_CORRUPTED		53//0xE1
#define TASK_NOT_STARTED			54//0xE4
#define SOFTWARE_COLDSTART			55//0xE5
#define CONFIGURATION_ERROR			56//0xE6	
#define BOARD_MEMORY_ERROR			57//0xE7
#define DATABASE_NOT_COMPATIBLE		58//0xE8
#define HARDWARE_COLDSTART			59//0xE9
#define NEW_SOFTWARE_VER_DETECTED	60//0xE10
#define TOTALIZER_CORRUPTED			61//0xE60
#define BOSS_DATABASE_CRC_INCORRECT 62//99
#define SOFTWARE_COLDSTART1			63//5034
#define HARDWARE_COLDSTART1			64//5035
#define DATABASE_CORRUPTED			65//5036
#define TOTALIZER_CORRUPTED1		66//5037
#define IFSFLONI_BOARD_NOT_CONNECTED 67//5088
#define ATCHUB_NOT_CONN_ENABLED		68//5091 
#define ATCHUB_CONN_DISABLED		69//5092		
#define DISPLAY_BOARD_COMM_FAILURE	70//5111
#define DISPLAY_BOARD_NOT_PRESENT	71//5113
#define DISPLAY_BOARD_ERROR			72//5130
#define STOP_BUTTON_STUCK			73//5139
#define ETOTE_BOARD_RETROFITTED		74//5175
#define SLAVE_DISP_COMM_FAULT		75//5211
#define FUEL_DENSITY_NOT_SET		76//5600
#define DISPLAY_SOFTWARE_ERROR_VER_CHANGED	77//5603
#define MULTIWIREBOARD_COMM_FAILURE 78//5700
#define MULTIWIREBOARD_UNCONFIGURED 79//5701
#define	MULTIWIREBOARD_DEVICE_ERROR	80//5702
#define HEAD_DOOR_SWITCH_OPEN		81//5721
#define HYDRAULIC_PANEL_SWITCH_OPEN	82//5723
#define CNG_OVER_PRESSURE_DETECTED	83//5801
#define CNG_SHOCK_SENSOR_ACTIVE		84//5802
#define CNG_AUSTRIAN_LEAK_TEST_ERROR	85//5820
#define CNG_AUSTRIAN_LPG_LEAK_TEST_ERROR	86//5827
#define CORIOLIS_METER_NOT_CONNECTED	87//5830
#define IS_INTERFACE_DISCONNECTED	88//6002
#define AABPIB_NOT_CONN_ENABLED		89//6006
#define ECALBOARD_NOT_CONN_ENABLED	90//6014
#define HOSE_LEAK_TEST_FAILED		91//6030
#define HOSE_LEAK_TEST_FAILED1		92//6031
#define HOSE_LEAK_TEST_INTERRUPTED	93//6032
#define TANK_LOW_LEVEL_ERROR		94//6035
#define AABPIB_NOT_DETECTED_SENSOR_ENABLED	95//6036
#define NOZZLEOUT_POWERUP_HOSELEAKTEST_NOT_POSSIBLE	96//6037
#define KIOSKSWITCH_NOT_CONN_ENABLED	97//6039
#define NEW_SOFTWARE_VER_DETECTED1	98//6086		
#define DISPENSER_WRONG_NOZZLE					99


#define MAX_PUMP_ALARMS DISPENSER_WRONG_NOZZLE		//CR 465678


//Pumps ANPR Alarms (Cat 2, Subcat 13)
#define ANPR_PUMP_BLOCKED					1
#define ANPR_PUMP_BLOCKED_NO_TRANSACTION    2




//Pumps Terminals Alarms (Cat 2, Subcat 1)
#define TREMINAL_NO_SPECIFIC_WARNING 1
//#define TERMOFFLINE_WARNING			2
#define TERMINAL_NO_SPECIFIC_ERROR	3
//#define TERMINAL_NO_ERROR			4    //TD 78557 - put in comment - should not be in use
#define TERMINAL_SECURITY_BRAKE     4    //TD 78557 - new for SPOT
#define TERMINAL_OFFLINE_WARNING	20 					


	

//Pumps Printer Alarms
#define PRINTER_OK					0
#define PRINETR_NON_SPECIFIC_ERROR  1
#define PAPER_LOW_WARNING			2
#define OUT_OF_PAPER_WARNING		3
#define PAPER_JAM_WARNING			4
#define PRINTER_COMPARTMENT_OPEN	6   //1.0.15.0

///#define AUDIT_OFFLINE				5
//#define AUDIT_OUT_OF_PAPER			6
//#define AUDIT_GENERAL_ERROR			7

#define PRINTER_OFFLINE_WARNING	     20 					

//Pumps keyboard (CAT 2, sub 4)
#define PINPAD_HW_ERROR			    1 					

//Pumps terminal display (CAT 2, sub 5)
#define TERMINAL_GENERAL_DISPLAY_ERROR 1  //TD 78557 - new for SPOT

//Pumps Cash Acceptor Alarms (CAT 4, sub 4)
#define CASH_ERROR_NOT_SPECIFIC		1

// merge from 1017
// #define CASH_REJECTED_WARNING		2
// #define CASH_JAMMED_WARNING			3
// #define CASH_CASSETT_FULL_WARNING	4
// #define CASH_CASSETT_REMOVE_WARNING	5
// #define CASH_READER_ERR				6

#define CASH_REJECTED_WARNING		5
#define CASH_JAMMED_WARNING			6
#define CASH_CASSETT_FULL_WARNING	7
#define CASH_CASSETT_REMOVE_WARNING	8
#define CASH_READER_ERR				9


#define CASH_IPT_DOOR_OPENED		10
#define CASH_ESCROW_ERROR			11
#define CASH_ACCEPTOR_PAPER_LOW     12



#define CASH_ACC_OFFLINE_WARNING	20 					

//Pumps Card encryption Alarms
#define CARD_ENCRYPTION_WARNING		2

#define CARD_ENCRYPTION_OFFLINE_WARNING	20 					

//Pumps RFID_ANTENNA Alarms
#define TAG_ERROR_NOT_SPRCIFIC		1
#define	CHALLANGE_FAIL_ERR			2
#define	TAG_GONE_ERR				3
#define	TAG_NOT_FOUND_ERR			4
#define	TAG_CHANGED_ERR				5
#define	TAG_READ_ERR				6
#define	CAR_TAG_READ_ERR			7
#define	HAND_TAG_READ_ERR			8
#define	TAG_CANCELLED_ERR			9
#define	GENERAL_SPEED_PASS_DECLINE	10			
#define	TAG_SALE_CANCELED			11
#define	TAG_SALE_DECLINED			12

#define RFID_OFFLINE_WARNING		20

//Encription device
#define ENCRYPTION_ERROR_NO_SPECIFIC 1  //1.0.0.17


//Pumps Card reader Alarms
#define CARD_READER_NON_SPECIFIC_ERROR	1
#define CARD_READER_ERR				2
#define SOFT_DECLINE				3
#define HARD_DECLINE				4
#define PAP_SWIPE_WHILE_UNPAID_PAK_TRANSACTIONS	5


#define CARD_READEROFFLINE_WARNING	20


	// Pump price change sub category
	#define PRICE_SUCCESSFUL_CHANGE_POSITION1_CASH_LEVEL_FULL_SERVICE		1
	#define PRICE_SUCCESSFUL_CHANGE_POSITION2_CASH_LEVEL_FULL_SERVICE		2
	#define PRICE_SUCCESSFUL_CHANGE_POSITION3_CASH_LEVEL_FULL_SERVICE		3
	#define PRICE_SUCCESSFUL_CHANGE_POSITION4_CASH_LEVEL_FULL_SERVICE		4
	#define PRICE_SUCCESSFUL_CHANGE_POSITION5_CASH_LEVEL_FULL_SERVICE		5
	#define PRICE_SUCCESSFUL_CHANGE_POSITION6_CASH_LEVEL_FULL_SERVICE		6
	#define PRICE_SUCCESSFUL_CHANGE_POSITION7_CASH_LEVEL_FULL_SERVICE		7
	#define PRICE_SUCCESSFUL_CHANGE_POSITION8_CASH_LEVEL_FULL_SERVICE		8


	#define PRICE_SUCCESSFUL_CHANGE_POSITION1_CREDIT_LEVEL_FULL_SERVICE		9
	#define PRICE_SUCCESSFUL_CHANGE_POSITION2_CREDIT_LEVEL_FULL_SERVICE		10
	#define PRICE_SUCCESSFUL_CHANGE_POSITION3_CREDIT_LEVEL_FULL_SERVICE		11
	#define PRICE_SUCCESSFUL_CHANGE_POSITION4_CREDIT_LEVEL_FULL_SERVICE		12
	#define PRICE_SUCCESSFUL_CHANGE_POSITION5_CREDIT_LEVEL_FULL_SERVICE		13
	#define PRICE_SUCCESSFUL_CHANGE_POSITION6_CREDIT_LEVEL_FULL_SERVICE		14
	#define PRICE_SUCCESSFUL_CHANGE_POSITION7_CREDIT_LEVEL_FULL_SERVICE		15
	#define PRICE_SUCCESSFUL_CHANGE_POSITION8_CREDIT_LEVEL_FULL_SERVICE		16

	#define PRICE_SUCCESSFUL_CHANGE_POSITION1_CASH_LEVEL_SELF_SERVICE		17
	#define PRICE_SUCCESSFUL_CHANGE_POSITION2_CASH_LEVEL_SELF_SERVICE		18
	#define PRICE_SUCCESSFUL_CHANGE_POSITION3_CASH_LEVEL_SELF_SERVICE		19
	#define PRICE_SUCCESSFUL_CHANGE_POSITION4_CASH_LEVEL_SELF_SERVICE		20
	#define PRICE_SUCCESSFUL_CHANGE_POSITION5_CASH_LEVEL_SELF_SERVICE		21
	#define PRICE_SUCCESSFUL_CHANGE_POSITION6_CASH_LEVEL_SELF_SERVICE		22
	#define PRICE_SUCCESSFUL_CHANGE_POSITION7_CASH_LEVEL_SELF_SERVICE		23
	#define PRICE_SUCCESSFUL_CHANGE_POSITION8_CASH_LEVEL_SELF_SERVICE		24


	#define PRICE_SUCCESSFUL_CHANGE_POSITION1_CREDIT_LEVEL_SELF_SERVICE		25
	#define PRICE_SUCCESSFUL_CHANGE_POSITION2_CREDIT_LEVEL_SELF_SERVICE		26
	#define PRICE_SUCCESSFUL_CHANGE_POSITION3_CREDIT_LEVEL_SELF_SERVICE		27
	#define PRICE_SUCCESSFUL_CHANGE_POSITION4_CREDIT_LEVEL_SELF_SERVICE		28
	#define PRICE_SUCCESSFUL_CHANGE_POSITION5_CREDIT_LEVEL_SELF_SERVICE		29
	#define PRICE_SUCCESSFUL_CHANGE_POSITION6_CREDIT_LEVEL_SELF_SERVICE		30
	#define PRICE_SUCCESSFUL_CHANGE_POSITION7_CREDIT_LEVEL_SELF_SERVICE		31
	#define PRICE_SUCCESSFUL_CHANGE_POSITION8_CREDIT_LEVEL_SELF_SERVICE		32


	// fail section
	#define PRICE_FAILED_CHANGE_POSITION1_CASH_LEVEL_FULL_SERVICE		33
	#define PRICE_FAILED_CHANGE_POSITION2_CASH_LEVEL_FULL_SERVICE		34
	#define PRICE_FAILED_CHANGE_POSITION3_CASH_LEVEL_FULL_SERVICE		35
	#define PRICE_FAILED_CHANGE_POSITION4_CASH_LEVEL_FULL_SERVICE		36
	#define PRICE_FAILED_CHANGE_POSITION5_CASH_LEVEL_FULL_SERVICE		37
	#define PRICE_FAILED_CHANGE_POSITION6_CASH_LEVEL_FULL_SERVICE		38
	#define PRICE_FAILED_CHANGE_POSITION7_CASH_LEVEL_FULL_SERVICE		39
	#define PRICE_FAILED_CHANGE_POSITION8_CASH_LEVEL_FULL_SERVICE		40


	#define PRICE_FAILED_CHANGE_POSITION1_CREDIT_LEVEL_FULL_SERVICE		41
	#define PRICE_FAILED_CHANGE_POSITION2_CREDIT_LEVEL_FULL_SERVICE		42
	#define PRICE_FAILED_CHANGE_POSITION3_CREDIT_LEVEL_FULL_SERVICE		43
	#define PRICE_FAILED_CHANGE_POSITION4_CREDIT_LEVEL_FULL_SERVICE		44
	#define PRICE_FAILED_CHANGE_POSITION5_CREDIT_LEVEL_FULL_SERVICE		45
	#define PRICE_FAILED_CHANGE_POSITION6_CREDIT_LEVEL_FULL_SERVICE		46
	#define PRICE_FAILED_CHANGE_POSITION7_CREDIT_LEVEL_FULL_SERVICE		47
	#define PRICE_FAILED_CHANGE_POSITION8_CREDIT_LEVEL_FULL_SERVICE		48

	#define PRICE_FAILED_CHANGE_POSITION1_CASH_LEVEL_SELF_SERVICE		49
	#define PRICE_FAILED_CHANGE_POSITION2_CASH_LEVEL_SELF_SERVICE		50
	#define PRICE_FAILED_CHANGE_POSITION3_CASH_LEVEL_SELF_SERVICE		51
	#define PRICE_FAILED_CHANGE_POSITION4_CASH_LEVEL_SELF_SERVICE		52
	#define PRICE_FAILED_CHANGE_POSITION5_CASH_LEVEL_SELF_SERVICE		53
	#define PRICE_FAILED_CHANGE_POSITION6_CASH_LEVEL_SELF_SERVICE		54
	#define PRICE_FAILED_CHANGE_POSITION7_CASH_LEVEL_SELF_SERVICE		55
	#define PRICE_FAILED_CHANGE_POSITION8_CASH_LEVEL_SELF_SERVICE		56


	#define PRICE_FAILED_CHANGE_POSITION1_CREDIT_LEVEL_SELF_SERVICE		57
	#define PRICE_FAILED_CHANGE_POSITION2_CREDIT_LEVEL_SELF_SERVICE		58
	#define PRICE_FAILED_CHANGE_POSITION3_CREDIT_LEVEL_SELF_SERVICE		59
	#define PRICE_FAILED_CHANGE_POSITION4_CREDIT_LEVEL_SELF_SERVICE		60
	#define PRICE_FAILED_CHANGE_POSITION5_CREDIT_LEVEL_SELF_SERVICE		61
	#define PRICE_FAILED_CHANGE_POSITION6_CREDIT_LEVEL_SELF_SERVICE		62
	#define PRICE_FAILED_CHANGE_POSITION7_CREDIT_LEVEL_SELF_SERVICE		63
	#define PRICE_FAILED_CHANGE_POSITION8_CREDIT_LEVEL_SELF_SERVICE		64


	#define ALL_PRICE_CHANGES_SUCCEEDED									65
	#define PRICE_CHANGES_PROCESS_FAILED								66

	#define PRICE_CHANGE_START											67 
	#define PRICE_CHANGE_SUCCESS										68
	#define PRICE_CHANGE_WAS_NOT_APPLIED								69 //4.0.13.502
	#define PRICE_CHANGE_ENDED											70 //4.0.26.508 147183
	#define PRICE_CHANGE_NO_CHANGE										71


// Pump scanner
#define SCANNER_NOT_COMMUNICATING    1   //1.0.15.0

//Devices Car wash Alarms
#define CARWASH_NON_SPECIFIC_ERROR   1
#define CARWASH_OFFLINE_WARNING		 20

//Devices AVI alarms
#define AVI_NON_SPECIFIC_ERROR       1
#define AVI_OFFLINE_WARNING		     20

//Devices Price Pole alarms
#define PRICE_POLE_NON_SPECIFIC_ERROR		  1
#define PRICE_POLE_BLANKED_FAILED_WARNING     3
#define PRICE_POLE_PRICE_CHANGE_FAILED        4
#define PRICE_POLE_OFFLINE_WARNING		      20

//Deviced ITL alarms
#define ITL_CLEAR_DELIVERY_FAIL				1
#define ITL_TRANSACTION_STUCK_IN_DEVICE		2
#define ITL_NON_SPECIFIC_ERROR				20	


//device UPS
#define UPS_NON_SPECIFIC_ERROR   1
#define UPS_IS_ACTIVE			 2

//device  C&P 
#define CHIP_AND_PIN_NOT_SPECIFIC_WARNING					1
#define CHIP_AND_PIN_SOFTWARE_UPDATE_TO_OPT_STARTED			2
#define CHIP_AND_PIN_SOFTWARE_UPDATE_TO_OPT_COMPLETED		3
#define CHIP_AND_PIN_SOFTWARE_UPDATE_TO_OPT_FAILED			4
#define CHIP_AND_PIN_PUSH_CARD_INTO_THE_READER				5
#define CHIP_AND_PIN_ERROR_READING_CARD_ON_PAP				6
#define CHIP_AND_PIN_ERROR_READING_CARD_ON_REPRINT			7	
#define CHIP_AND_PIN_CARD_REMOVED_TOO_SOON					8
#define CHIP_AND_PIN_BAD_CHIP								9
#define CHIP_AND_PIN_CARD_CANCELLED							10
#define CHIP_AND_PIN_NO_VALID_APPLICATIONS					11
#define CHIP_AND_PIN_CHIP_ERROR								12
#define CHIP_AND_PIN_CHIP_TIME_OUT_TO_REMOVE_CARD			13
#define CHIP_AND_PIN_CHIP_OPT_TAMPERED						14


//Device ANPR (Cat 4, sub 10)
#define DEVICE_ANPR_OFFLINE         						20


/******************************************
	SOFTWARE ALARMS		
*******************************************/
//PumpSrv Alarms
#define SOFTWARE_NO_ERROR					0
#define SOFTWARE_CONFIGURATION_ERR			1
#define SOFTWARE_HARDWARE_ERR				2
#define SOFTWARE_ERR						3
#define SOFTWARE_COM_ERR					4
#define SOFTWARE_TANK_CONFIGURATION_ERR		5
#define SOFTWARE_MISSING_TANK_READING_ERR	6
#define SOFTWARE_NO_CONTROLLER				7
#define SOFTWARE_NO_CONVERT_LAYER			8
//#define SOFTWARE_SHUTDOWN_TASK				8
//#define SOFTWARE_SHUTDOWN_CONFIGURATION		9
//#define SOFTWARE_SHUTDOWN_LEFT				10
#define SOFTWARE_PROCESS_LOCK				11
#define SOFTWARE_ENCRYPTION_LOAD_FAIL		12
#define SOFTWARE_GENERAL_OLA_ERR			13
#define SOFTWARE_DISK_FULL_WARNING			14
#define SOFTWARE_DISK_FULL_ERR				15
//#define SOFTWARE_POWER_WARNING				16
#define SOFTWARE_POWER_FAILED				17
//#define SOFTWARE_SHUTDOWN_POS				18
//#define SOFTWARE_SHUTDOWN_POWER				19

#define PUMP_TOTAL_READING_FAILED			22 //
#define PAP_TRS_IN_OLA_QDX					23
#define ALARM_FORECOURT_IN_MAINTENANCE		24 //4.0.12.507
#define DATABASE_MAINTENANCE_TIMEOUT		25 //4.0.13.502
#define NEXT_SHIFT_INCLUDES_RELOAD			26 //33898
#define DSS_INIT_FAIL						27 //4.0.20.501 TD 60236
#define DSS_HASHING_FAIL					28	//4.0.22.40	TD 72716
#define DSS_ENCRYPTION_FAIL					29	//4.0.22.40	TD 72716
#define DSS_STORE_MODE_CHANGED				30	//4.0.22.40	TD 72716
#define DSS_REINIT_CALLED					31	//4.0.22.40	TD 72716
#define PCI_PARAMETER_CHANGED				32	//4.0.22.504	TD 72716
#define GOT_COMMIT_PRICE_CHANGE_COMMAND		33  //4.0.26.508 147183
#define ALARM_EMPTY_QDX						34  //4.0.27.500 TD 236009
#define ALARM_TRS_FORCE_REMOVE				35	//4.0.27.500 TD 236009
#define ALARM_VP_IS_DOWN                    36  //4.0.25.354   TD 264908
#define FAILED_TO_PROCESS_FUEL_CONFIGURATION_XML	37//CR 407467 
#define	CONFIGURATION_THREAD_FAIL			        38  //4.0.28.340   TD 419618 

//FCC Alarms
#define SOFTWARE_PCI_COMPLIANT_CHANGED		1	//Shuki (TD 52440) 4.0.20.502

//Meggit Alarm
#define MEGGIT_SYS_POWER_WARNING			1
#define MEGGIT_SYS_POWER_FAILED				2
#define MEGGIT_SYS_AUDIT_OFFLINE			3
#define MEGGIT_SYS_AUDIT_OUT_OF_PAPER		4
#define MEGGIT_SYS_AUDIT_GENERAL_ERROR		5
#define MEGGIT_SYS_ERROR_CONFIG				6
#define MEGGIT_SYS_SHUTDOWN_POS				7
#define MEGGIT_SYS_SHUTDOWN_POWER			8
#define MEGGIT_SYS_SHUTDOWN_TASK			9
#define MEGGIT_SYS_SHUTDOWN_CONFIG			10
#define MEGGIT_SYS_SHUTDOWN_I2C				11
#define MEGGIT_SYS_SHUTDOWN_LEFT			12
#define MEGGIT_SYS_NO_ERROR					13


//Allied  Sys Alarm
#define ALLIED_SYS_ERROR_COMM				1
#define ALLIED_SYS_ERROR_NON_SPECIFIC		2
#define ALLIED_SYS_ERROR_HW					3	
#define ALLIED_SYS_ERROR_SW					4	
#define ALLIED_SYS_ERROR_DELIVERY_FILE_FULL	5

//RFS  Sys Alarm
#define RFS_GRADE_DISCOUNT_BIGGER_PRICE					1
#define RFS_GRADE_ACTUAL__PRICE_DIFF_CONFIG_PRICE		2
#define RFS_CARD_ALREADY_SWIPE							5
#define RFS_TOO_MANY_ATTEMPT_REPRINT					6
#define RFS_TOO_MANY_ATTEMPT_SWIPE						7
#define RFS_WRONG_ROLLING_UPDATES                       8 //TD 67886
#define RFS_WET_STOCK_REPORT_REQUESTED					9 //TD 144355


//Postec sys Alarm
#define POSTEC_PIPI_OFFLINE					1
#define POSTEC_PROM_FAILED					2
#define POSTEC_RAM_FAILED					3
#define POSTEC_PCC_EXTERNAL_RAM_FAILED		4
#define POSTEC_EMERGENCY_STOP				5
#define POSTEC_CORRUPTED_MESSAGE_FROM_EFT	6

//Wayne sys Alarm
#define WAYNE_CONTROLLER_CONNECTED			1
#define WAYNE_CONTROLLER_DISCONNECTED		2
#define WAYNE_RECEIPT_PAPER_LOW     		3
#define WAYNE_RECEIPT_OUT_OF_PAPER     		4
#define WAYNE_TERMINAL_DOOR_OPEN     		5
#define WAYNE_TERMINAL_DOOR_CLOSED     		6
#define WAYNE_PIN_PAD_ERROR					7
#define WAYNE_CARD_READER_ERROR				8
	
//Htec sys alarms (SUB_HTEC) //4.0.27.500
#define HTEC_FAILED_TO_INIT_PUMP_ANPR_OCX		1
#define HTEC_FAILED_TO_INIT_OPT_OCX				2
#define HTEC_FAILED_TO_INIT_TANKS_OCX			3
#define HTEC_FAILED_TO_INIT_CODAX_OCX			4

//general decline 
//For All Device Categort
#define NO_SPECIFIC_ERROR					1

#define OFFLINE_WARNING						20

//PAPCON warnings
#define CUSTOMER_CANCELED_TRANSACTION		2

//Online Services warnings
#define OLA_CLOSE_BATCH_SUCCESS				1
#define OLA_CLOSE_BATCH_FAILURE				2
#define PAP_NOT_AVAILABLE					3
#define INIT_DEBIT_SUCCESSFUL				4
#define INIT_DEBIT_FAILED					5


//MultiSync Alarms (SubCategory 6)
#define MS_CONNECTION_FAILED	1
#define MS_NOT_SYNC				2
#define MS_QDEX_PROBLEM			3

// Qdex- Alarm sub Category 7  
#define QDX_FATAL_ERROR						1
#define QDX_ERR_DELETED						2
#define QDX_ERR_EXISTS						3
#define QDX_ERR_DISK_READ					4
#define QDX_ERR_DISK_WRITE					5
#define QDX_ERR_FILE_FULL					6
#define QDX_ERR_QDX_NOT_OPEN				7
#define QDX_MAINTENANCE						8	//4.0.18.20

//ATS -Alarm sub category 8
#define ATS_ALARM_LOST_CONNECTION				1
#define ATS_ALARM_SWITCH_TO_SECONDARY			2
//4.0.14.503
#define ATS_AUTO_SWITCH_WARNING_TIMER_ELAPSED	3
#define ATS_AUTO_SWITCH_RESTORED_BEFORE_SWITCH	4
#define ATS_AUTO_SWITCH_STARTED					5
#define ATS_AUTO_SWITCH_COMPLETED				6
#define ATS_AUTO_SWITCH_FAILED					7
#define ATS_ALARM_KILL_PUMPSRV_WORKAROUND		8
#define ATS_ALARM_RELOAD_CL						9		// TD 89047
#define ATS_ALARM_RELOAD_TCPCOM					10		// TD 89047


/******************************************
	DEVICES ALARMS		
*******************************************/

//Price sign Alarms

//4.0.12.515
//4.0.21.0
//#define PRICE_CHANGE_FAILURE				3
#define GRADE_PRICE_UPDATE_SUCCESS			1//2.0.17.500
#define GRADE_PRICE_UPDATE_FAILURE			2//2.0.17.500
#define SET_CONTROLLER_DATETIME_SUCCESS		3
#define SET_CONTROLLER_DATETIME_FAILURE		4
#define SET_PRICE_BATCH_FAILED				5



/******************************************
	ALARMSRV INTERNAL ALARMS		
*******************************************/

//Encoding alarms
#define ENCODING_INITIALIZATION_FAILED				1
#define ENCODING_VERIFY_FILE_SIGNATURE_FAILED		2
#define ENCODING_CREATE_FILE_SIGNATURE_FAILED		3
#define REACHED_MAX_ALARM_COUNTER					4

#define SQL_GENERAL_ERROR    1
#define SQl_DB_NOT_RUNNING	 2


#endif //_ALARM_CLASS_
