#ifndef __XML_DEFINITIONS_H__
#define __XML_DEFINITIONS_H__


//Define the attributes in the xml buffer of card sale data.

//Data

#define		ATT_TRAN_TYPE					"CardData\\TranType"
#define		ATT_MID							"CardData\\MID"
#define		ATT_PUMP_NUMBER					"CardData\\PumpNumber"
#define		ATT_DEVICE_NUMBER				"CardData\\DeviceNumber"
#define		ATT_TRAN_NBR					"CardData\\TranNbr"
#define		ATT_REQUEST_AMT					"CardData\\RequestAmt"
#define		ATT_TRAN_STATUS					"CardData\\CSDTranStatus"
#define		ATT_TRACK1_DATA					"CardData\\Track1Data"
#define		ATT_TRACK2_DATA					"CardData\\Track2Data"
#define		ATT_CARD_TYPE					"CardData\\CSDCardType"
#define		ATT_AUTHORIZE_SESSION_ID		"CardData\\AuthorizeSessionID"
#define		ATT_ACCOUNT_NUMBER				"CardData\\CSDAccountNumber"
#define		ATT_FULL_CARD_NAME				"CardData\\CSDFullCardName"
#define		ATT_CLUB_CARD_TRACK2_DATA		"CardData\\ClubCardTrack2Data"
#define		ATT_CARD_NAME					"CardData\\CardName"	
#define		ATT_GR_PROMPT					"CardData\\GRPrompt"
#define		ATT_FULL_VEHICLE_ID				"CardData\\CSDFullVehicleId"
#define		ATT_AUTH_AMT					"CardData\\AuthAmt"
#define		ATT_ATTANDANT_SESSION			"CardData\\AttandantSession"
#define		ATT_FORCE_COMPLETE_ZERO		    "CardData\\ForceCompleteZero"
#define		ATT_ODOMETER				    "CardData\\CSDOdometer"
#define		ATT_PIN_BLOCK				    "CardData\\PINBlock"
#define		ATT_RETURN_TANK				    "CardData\\ReturnTank"
#define		ATT_DRIVER_ID				    "CardData\\DriverId"
#define		ATT_GR_VOUCHER_NUMBER		    "CardData\\GRVoucherNumber"
#define		ATT_GR_KEY_CODE				    "CardData\\GRKeyCode"
#define		ATT_GENERAL_ID				    "CardData\\GeneralID"
#define		ATT_REFERENCE_NUMBER		    "CardData\\CSDReferenceNumber"
#define		ATT_AUTH_NUMBER				    "CardData\\CSDAuthNumber"
#define		ATT_GRADE_RESTRICTION		    "CardData\\GradeRestriction"
#define		ATT_NOZZLE_RESTRICTION		    "CardData\\NozzleRestriction"
#define		ATT_NOZZLE					    "CardData\\CSDNozzle"
#define		ATT_AVI_SYSTEM_CUSTOMER		    "CardData\\AVISystemCustomer"
#define		ATT_RESULT_MSG					"CardData\\ResultMsg"
#define		ATT_GR_MAX_VOLUME				"CardData\\GRMaxVolume"
#define		ATT_AUTH_CODE					"CardData\\AuthCode"
#define		ATT_APP_CODE_ELECTR				"CardData\\AppCodeElectr"
#define		ATT_IS_STORE_AND_FORWARD		"CardData\\IsStoreAndForward"
#define		ATT_SURCHARGE_AMT				"CardData\\SurchargeAmt"
#define		ATT_EXTEND_PIN					"CardData\\ExtendPIN"
#define		ATT_ENTRY_METHOD				"CardData\\EntryMethod"
#define		ATT_RESERVED					"CardData\\CSDReserved"
#define		ATT_START_DATE					"CardData\\StartDate"
#define		ATT_CARD_ISSUE					"CardData\\CardIssue"
#define		ATT_IS_ONLINE					"CardData\\CSDIsOnLine"
#define		ATT_CLEARANCE_ID				"CardData\\ClearanceID"
#define		ATT_DATE_TIME					"CardData\\CSDDateTime"
#define		ATT_MERCHANT_ID					"CardData\\MerchantID"
#define		ATT_RECEIPT_RESTRICTION			"CardData\\ReceiptRestriction"
#define		ATT_APPROVAL					"CardData\\Approval"
#define		ATT_RES_INFO_AMAX8				"CardData\\ResInfoAMax8"
#define		ATT_EXPIRE						"CardData\\CSDExpire"
#define		ATT_HOST_TERMINAL_ID			"CardData\\HostTerminalID"
#define		ATT_AVI_ENGINE_HOURS			"CardData\\AVIEngineHours"
#define		ATT_AVI_COMPANY_ID				"CardData\\AVICompanyId"
#define		ATT_AVI_USER_ID					"CardData\\AVIUserId"
#define		ATT_AVI_LIMIT					"CardData\\AVILimit"
#define		ATT_AVI_LIMIT_TYPE				"CardData\\AVILimitType"
#define		ATT_AVI_SPECIAL_CODES			"CardData\\AVISpecialCodes"
#define		ATT_FINAL_REF_NUMBER			"CardData\\FinalRefNumber"
#define		ATT_FINAL_AUTH_NUMBER			"CardData\\FinalAuthNumber"
#define		ATT_GR_DISCOUNT_PER_GALLON		"CardData\\GRDiscountPerGallon"
#define		ATT_AUTH_TERMINAL				"CardData\\AuthTerminal"
#define		ATT_AUTH_VERSION				"CardData\\AuthVersion"
#define		ATT_TRANS_BATCH					"CardData\\CSDTransBatch"
#define		ATT_TRANS_BATCH_SEQUENCE		"CardData\\TransBatchSequence"


//ExtData

#define		ATT_TOTAL_AMT					"CardData\\TotalAmt"
#define		ATT_REDEEM_POINTS				"CardData\\RedeemPoints"
#define		ATT_CONFIRM_PROMPT				"CardData\\ConfirmPrompt"
#define		ATT_TAX_AMT						"CardData\\TaxAmt"
#define		ATT_FUEL_AMT					"CardData\\FuelAmt"
#define		ATT_GR_TOTAL_DISCOUNT			"CardData\\GRTotalDiscount"
#define		ATT_GR_ACTUAL_DISCOUNT_PER_GALLON "CardData\\GRActualDiscountPerGallon"
#define		ATT_PRN_DATE_TIME				"CardData\\PrnDateTime"
#define		ATT_CAR_WASH_PROGRAM			"CardData\\CarWashProgram"
#define		ATT_WASH_CODE					"CardData\\WashCode"
#define		ATT_WASH_EXPIRE					"CardData\\WashExpire"
#define		ATT_LOYAL_ID					"CardData\\LoyalId"
#define		ATT_COUPON_REWARD				"CardData\\CouponReward"
#define		ATT_BAR_CODE					"CardData\\BarCode"
#define		ATT_LOYAL_SCHEME				"CardData\\LoyalScheme"
#define		ATT_LOYAL_POINTS				"CardData\\LoyalPoints"
#define		ATT_VAT_RATE					"CardData\\VAT_Rate"
#define		ATT_RECIPT_STATUS				"CardData\\ReciptStatus"
#define		ATT_EX_RESERVED					"CardData\\CSEDReserved"
#define		ATT_NUMBER_OF_EXTRA_SALE		"CardData\\NumberOfExtraSale"
#define		ATT_FUEL_AMT					"CardData\\FuelAmt"
#define		ATT_CAR_WASH_PROGRAM			"CardData\\CarWashProgram"
#define		ATT_BANK_TERM_ID				"CardData\\CSEDBankTermId"
#define		ATT_CUSTOMER_NAME				"CardData\\CSEDCustomerName"
#define		ATT_ISO_RESPONSE				"CardData\\CSEDISOResponse"
#define		ATT_SPDH_CODE					"CardData\\CSEDSPDHCode"
#define		ATT_LOYALTY_ACTIVE				"CardData\\LoyaltyActive"
#define		ATT_DATE_TIME_EXT				"CardData\\DateTimeExt"
#define		ATT_COMPLETE_DATE				"CardData\\CompleteDate"
#define		ATT_COMPLETE_TIME				"CardData\\CompleteTime"
#define		ATT_ATTANDANT_SESSION			"CardData\\AttandantSession"
#define		ATT_SLIP_FLAGS					"CardData\\CSEDSlipFlags"
#define		ATT_ODOMETER_EXT				"CardData\\OdometerExt"

#define		ATT_SALE_ID						"CardData\\Sales\\Sale\\ID"


//ExtraData2

#define		ATT_SITE_ID						"CardData\\CSEDSiteId"
#define		ATT_CUSTOMER_REFERENCE			"CardData\\CustomerReference"
#define		ATT_CLOCK_FLAGS					"CardData\\ClockFlags"
#define		ATT_FLAGS						"CardData\\Flags"
#define		ATT_COMPLETE_SESSION_ID			"CardData\\CompletedSessionID"
#define		ATT_SESSION_OFFLINE				"CardData\\SessionOffLine"
#define		ATT_CALCULATED_MAC				"CardData\\CalculatedMAC"
#define		ATT_MAC_SESSION_KEY				"CardData\\MACSessionKey"
#define		ATT_PIN_PAD_ACTION				"CardData\\PinPadAction"
#define		ATT_PIN_PAD_RESULT				"CardData\\PinPadResult"
#define		ATT_PIN_SESSION_KEY				"CardData\\PinSessionKey"
#define		ATT_TOKEN						"CardData\\Token"
#define		ATT_MESSAGE_TIME_OUT			"CardData\\MessageTimeOut"
#define		ATT_DECLINED_LOYALTY_PROMPT		"CardData\\DeclinedLoyaltyPrompt"
#define		ATT_ORIGIN_TRANS				"CardData\\OriginTrans"
#define		ATT_VOLUME_LIMIT				"CardData\\VolumeLimit"
#define		ATT_MEDIA_MASTER_TYPE			"CardData\\MediaMasterType"
#define		ATT_PARAM1						"CardData\\Param1"
#define		ATT_PARAM2						"CardData\\Param2"
#define		ATT_UNIT						"CardData\\Unit"
#define		ATT_TRIP_NUMBER					"CardData\\TripNumber"
#define		ATT_TRACTOR_HUB					"CardData\\TractorHub"
#define		ATT_TRAILER_NUMBER				"CardData\\TrailerNumber"
#define		ATT_TRAILER_HUB					"CardData\\TrailerHub"
#define		ATT_PASS_CODE					"CardData\\PassCode"
#define		ATT_SERVICE_FEE					"CardData\\ServiceFee"
#define		ATT_GRADE_PRICE					"CardData\\CSEDGradePrice"
#define		ATT_DECLINED_LOYALTY_RESPONSE	"CardData\\DeclinedLoyaltyResponse"
#define		ATT_CHARGE_TO					"CardData\\ChargeTo"
#define		ATT_ZIP_CODE					"CardData\\ZipCode"
#define		ATT_ACCOUNT_TYPE				"CardData\\CSEDAccountType"
#define		ATT_SCRIP_UNIT_PRICE			"CardData\\ScripUnitPrice"
#define		ATT_MARGIN_UNIT_PRICE			"CardData\\MarginUnitPrice"
#define		ATT_TOTAL_SCRIP_AMOUNT			"CardData\\TotalScripAmount"
#define		ATT_CUSTOMER_MESSAGE			"CardData\\CustomerMessage"
#define		ATT_COUPON_MESSAGE				"CardData\\CSEDCouponMessage"
#define		ATT_RESERVE_FOR_COUPON			"CardData\\CSEDReserveForCoupon"
#define		ATT_COUPON_ID					"CardData\\CouponId"
#define		ATT_LOYALTY_PROG_NAME			"CardData\\LoyaltyProgName"
#define		ATT_GR_DISCOUNT_TYPE			"CardData\\GRDiscountType"
#define		ATT_RECEIPT_TYPE				"CardData\\CSEDReceiptType"
#define		ATT_PRINTER_WIDTH				"CardData\\PrinterWidth"
#define		ATT_PARAM_NUMBER				"CardData\\ParamNumber"
#define		ATT_PAYMENT_STAGE				"CardData\\PaymentStage"
#define		ATT_TEXT_LENGTH					"CardData\\TextLength"
#define		ATT_FORMATTED_ACCOUNT			"CardData\\FormattedAccount"
#define		ATT_AUTO_AUTHORIZE				"CardData\\AutoAuthorize"
#define		ATT_WAIT_FOR_REPORT_FLAG		"CardData\\WaitForReportFlag"
#define		ATT_INVOICE_NUMBER				"CardData\\CSEDInvoiceNumber"
#define		ATT_AUTHORIZATION_SERIAL_NUMBER	"CardData\\CSEDAuthorizationSerialNumber"
#define		ATT_AUTHORIZER_FILE_NUMBER		"CardData\\CSEDAuthorizerFileNumber"
#define		ATT_LANGUAGE					"CardData\\Language"
#define		ATT_PROMOTION_NUMBER			"CardData\\PromotionNumber"
#define		ATT_PRICE_LEVEL					"CardData\\PriceLevel"
#define		ATT_SIGNATURE_SLIP				"CardData\\CSEDSignatureSlip"
#define		ATT_RECEIPT_PRINTED				"CardData\\ReceiptPrinted"
#define		ATT_RES_INFO_AMAX37				"CardData\\ResInfoAMax37"
#define		ATT_TOTAL_DISCOUNT				"CardData\\TotalDiscount"
#define		ATT_PRICE_RECALC_DISCOUNT_SIGN	"CardData\\PriceRecalcDiscountSign"
#define		ATT_SIGNATURE_SLIP				"CardData\\CSEDSignatureSlip"
#define		ATT_RECEIPT_PRINTED				"CardData\\ReceiptPrinted"
#define		ATT_TOTAL_BALANCE				"CardData\\TotalBalance"
#define		ATT_ATTENDANT_ID				"CardData\\AttendantID"
#define		ATT_ATTENDANT_NAME				"CardData\\AttendantName"
#define		ATT_IGNORE_SERVICE_FEE			"CardData\\IgnoreServiceFee"
#define		ATT_CLOCK_DATE_TIME				"CardData\\ClockDateTime"
#define		ATT_ITEMS_LINK_INDEX			"CardData\\ItemsLinkIndex"
#define		ATT_BAR_CODE					"CardData\\BarCode"
#define		ATT_TAX_AMT3					"CardData\\TaxAmt3"
#define		ATT_CASH_DEPOSIT1				"CardData\\CashDeposit1"
#define		ATT_CASH_DEPOSIT2				"CardData\\CashDeposit2"
#define		ATT_CASH_DEPOSIT5				"CardData\\CashDeposit5"
#define		ATT_CASH_DEPOSIT10				"CardData\\CashDeposit10"
#define		ATT_CASH_DEPOSIT20				"CardData\\CashDeposit20"
#define		ATT_CASH_DEPOSIT50				"CardData\\CashDeposit50"
#define		ATT_CASH_DEPOSIT100				"CardData\\CashDeposit100"
#define		ATT_CASH_DEPOSIT_TOTAL			"CardData\\CashDepositTotal"
#define		ATT_AUTHORIZER_ID				"CardData\\AuthorizerID"
#define		ATT_LOYALTY_TOTAL_AMOUNT		"CardData\\LoyaltyTotalAmount"
#define		ATT_DISPLAY_OLA_RESULT_MESSAGE	"CardData\\DisplayOLAResultMessage"
#define		ATT_AVI_FUEL_CODE				"CardData\\AVIFuelCode"
#define		ATT_PRICE_RECALC_DISCOUNT		"CardData\\PriceRecalcDiscount"

//ExtraData3

#define		ATT_FLAGS1						"CardData\\Flags1"
#define		ATT_RESEND						"CardData\\ReSend" 
#define		ATT_WAIT_FOR_PRICE_CHANGE		"CardData\\WaitForPriceChange" 
#define		ATT_PARAM_RESULT				"CardData\\ParamResult" 
#define		ATT_REMOTE_ID					"CardData\\RemoteID" 
#define		ATT_LOGIC_SHIFT_NUMBER			"CardData\\CSEDLogicShiftNumber" 
#define		ATT_COMBINED_CARD_SELECT		"CardData\\CombinedCardSelect" 
#define		ATT_CVM_RESULT					"CardData\\CVMResult" 
#define		ATT_TERM_RESPONSE_CODE			"CardData\\TermResponseCode" 
#define		ATT_ITEM_RESTRICTION			"CardData\\ItemRestriction" 
#define		ATT_REEFER_TOTAL				"CardData\\ReeferTotal" 
#define		ATT_REEFER_VOLUME				"CardData\\ReeferVolume" 
#define		ATT_TOTAL_REDEEMED_POINTS		"CardData\\CSEDTotalRedeemedPoints" 
#define		ATT_AMOUNT_BY_POINTS			"CardData\\CSEDAmountByPoints" 
#define		ATT_CREDIT_AMOUNT				"CardData\\CSEDCreditAmount" 
#define		ATT_CONTROLLER_SEQ_NUM			"CardData\\ControllerSeqNum" 
#define		ATT_CAR_WASH_DISCOUNT			"CardData\\CarWashDiscount" 
#define		ATT_CAR_WASH_LIMIT				"CardData\\CarWashLimit" 
#define		ATT_PROMPT_TYPE					"CardData\\PromptType" 
#define		ATT_PROMPT_MIN_LEN				"CardData\\PromptMinLen" 
#define		ATT_PROMPT_MAX_LEN				"CardData\\PromptMaxLen" 
#define		ATT_PARAM_INDEX					"CardData\\ParamIndex" 
#define		ATT_CARWASH_RESTRICTION			"CardData\\CarwashRestriction" 
#define		ATT_RESERVED_FOR_FUTURE_CARWASH	"CardData\\ReservedForfutureCarWash" 
#define		ATT_ORIGINAL_UNIT_PRICE			"CardData\\OriginalUnitPrice" 
#define		ATT_NON_DISCOUNT_TOTAL_AMOUNT	"CardData\\NonDiscountTotalAmount" 
#define		ATT_OFFLINE_TRANS				"CardData\\OfflineTrans" 
#define		ATT_REQUIRED_OLA_DATA			"CardData\\RequiredOlaData" 
#define		ATT_UNIT_PRICE_INCLUDE_DISCOUNT	"CardData\\UnitPriceIncludeDiscount" 
#define		ATT_THRESHOLD					"CardData\\Threshold" 
#define		ATT_THRESHOLD_TYPE				"CardData\\ThresholdType" 
#define		ATT_CLOCK_REQUIRED				"CardData\\ClockRequired" 
#define		ATT_RECEIPT_MODE				"CardData\\CSEDReceiptMode" 
#define		ATT_CUSTOMER_ID					"CardData\\CustomerID" 
#define		ATT_PREVIOUS_MEDIA_MASTER_TYPE	"CardData\\PreviousMediaMasterType" 
#define		ATT_MANAGER_ID					"CardData\\ManagerID" 
#define		ATT_DO_SESSION_AUTH				"CardData\\DoSessionAuth" 
#define		ATT_PMT_REFERENCE_NUMBER		"CardData\\PMTReferenceNumber" 
#define		ATT_DIESEL_LIMIT				"CardData\\DieselLimit" 
#define		ATT_REEFER_LIMIT				"CardData\\ReeferLimit" 
#define		ATT_CASH_BACK_LIMIT				"CardData\\CashBacklimit" 
#define		ATT_PROMPT_NAME					"CardData\\PromptName" 
#define		ATT_PROMPT_MODE					"CardData\\PromptMode" 
#define		ATT_PROMPT_ENCRYPTED			"CardData\\PromptEncrypted" 
#define		ATT_WAIT_PROMPT_NEED_MORE_PARAM	"CardData\\WaitPromptNeedMoreParam" 
#define		ATT_CL_FLAGS					"CardData\\ClFlags" 
#define		ATT_OPERATIONAL_PROMPT			"CardData\\OperationalPrompt" 
#define		ATT_RESTRICTION_ITEM_REQUIRED	"CardData\\RestrictionItemRequired" 
#define		ATT_DRY_ITEMS_RESTRICTION		"CardData\\DryItemsRestriction" 
#define		ATT_POSITION_RESTRICTION_ACTIVE	"CardData\\PositionRestrictionActive" 
#define		ATT_TRACK3_DATA					"CardData\\Track3Data" 
#define		ATT_AMOUNT_LIMIT_INCLUDES_CASH_BACK  "CardData\\AmountLimitIncludesCashBack" 
#define		ATT_DISPLAY_CASH_BACK_AMOUNT	"CardData\\DisplayCashBackAmount" 
#define		ATT_ALLOW_PARTIAL_CASH_BACK		"CardData\\AllowPartialCashBack" 
#define		ATT_OLA_BATCH_ID				"CardData\\OLABatchId" 
#define		ATT_CUSTOMER_VALIDATION_TYPE	"CardData\\CustomerValidationType" 
#define		ATT_PRE_SET_LIMIT				"CardData\\PreSetlimit" 
#define		ATT_PRE_SET_LIMIT_TYPE			"CardData\\PreSetlimitType" 
#define		ATT_TRUCKING_COMPANY_NAME		"CardData\\TruckingCompanyName" 
#define		ATT_MAG_CAPABILITIES			"CardData\\MagCapabilities" 
#define		ATT_ISSUE_NUMBER				"CardData\\IssueNumber" 
#define		ATT_TERMINAL_TYPE				"CardData\\TerminalType" 
#define		ATT_TERMINAL_COUNTRY_CODE		"CardData\\TerminalCountryCode" 
#define		ATT_TRANSACTION_CURRENCY_CODE	"CardData\\TransactionCurrencyCode" 
#define		ATT_AIP							"CardData\\AIP" 
#define		ATT_ATC							"CardData\\ATC" 
#define		ATT_TVR							"CardData\\TVR" 
#define		ATT_AID							"CardData\\AID" 
#define		ATT_AVN							"CardData\\AVN" 
#define		ATT_ISSUER_APPLICATION_DATA		"CardData\\IssuerApplicationData" 
#define		ATT_CRYPTOGRAM_INFO_DATA		"CardData\\CryptogramInfoData" 
#define		ATT_SCREEN_PROMPT				"CardData\\ScreenPrompt" 
#define		ATT_TIME_CARD_INSERTED			"CardData\\TimeCardInserted" 
#define		ATT_TIME_TRS_REQUIRED			"CardData\\TimeTRSRequired" 
#define		ATT_TIME_HC_RESPONSE			"CardData\\TimeHCResponse" 
#define		ATT_TIME_PIN_REQUEST			"CardData\\TimePINRequest" 
#define		ATT_TIME_OLA_REQUEST			"CardData\\TimeOLARequest" 
#define		ATT_TIME_OLA_RESULT				"CardData\\TimeOLAResult" 
#define		ATT_TIME_TNX_DETAILS			"CardData\\TimeTNXDetails" 
#define		ATT_ISSUER_ACTIONDES_DENIAL		"CardData\\IssuerActiondesDenial" 
#define		ATT_ISSUER_ACTIONDES_ONLINEL	"CardData\\IssuerActiondesOnLinel" 
#define		ATT_ISSUER_ACTIONDES_DEFAULT	"CardData\\IssuerActiondesDefault" 
#define		ATT_TRANSACTION_STATUS_MODE		"CardData\\TransactionStatusMode" 
#define		ATT_CONTROLLER_RESTRICTION		"CardData\\ControllerRestriction" 
#define		ATT_TAX_ID						"CardData\\TaxId" 
#define		ATT_LOYALTY_SESSION_ID			"CardData\\LoyaltySessionID" 
#define		ATT_AMOUNT_BY_POINTS2			"CardData\\AmountByPoints2" 
#define		ATT_PROMOTION_NUMBER2			"CardData\\PromotionNumber2" 
#define		ATT_OLA_QUALIFY_SPEND0			"CardData\\OLAQualifySpend0" 
#define		ATT_OLA_QUALIFY_SPEND1			"CardData\\OLAQualifySpend1" 
#define		ATT_CARD_HOLDER_VERIFY_METHOD	"CardData\\CardHolderVerifyMethod" 
#define		ATT_HOST_ONLINE_ID				"CardData\\HostOnLineID" 
#define		ATT_REASON_ONLINE_CODE			"CardData\\ReasonOnLineCode" 
#define		ATT_ISSUE_DATE					"CardData\\IssueDate" 
#define		ATT_PO_NUMBER					"CardData\\PONumber"	//4.0.15.502
#define		ATT_CARD_SEGMENT				"CardData\\CardSegment"	//Liat LPE

//ExtraData4
#define		ATT_LOYALTY_ON_OFF				"CardData\\LoyaltyOnOff"	//LPE
#define		ATT_EXTENDED_ZIP_CODE			"CardData\\ExtendedZipCode"	//46512
#define		ATT_ENCRYPTED_ACCOUNT			"CardData\\EncryptedAccount"		//4.0.20.501 TD 60236
#define		ATT_ENCRYPTED_ACCOUNT2			"CardData\\EncryptedAccount2"		//4.0.20.501 TD 60236
#define		ATT_DSS_FAILED					"CardData\\DSSFailed"				//4.0.20.501 TD 60236
#define		ATT_REMOVE_PROHIBITED_DATA		"CardData\\RemoveProhibitedData"	//4.0.20.501 TD 60236

//Elements
#define		ELEMENT_SALE					"CardData\\Sales\\Sale"
#define		ELEMENT_DISCOUNT				"CardData\\Discounts\\Discount"
#define		ELEMENT_LIMIT					"CardData\\Limits\\Limit"


#define		ATT_ID							"ID"	


//Sale attributes
#define		ATT_SALE_UNIT_PRICE				"UnitPrice"	
#define		ATT_DPT_PROD_CODE				"DPTProdCode"	

//Discount attributes
#define		ATT_DISCOUNT					"Discount" 

//Limit attributes

#define		ATT_GRADE_AMOUNT_LIMIT			"GradeAmountLimit"
#define		ATT_GRADE_ID					"GradeID"
#define		ATT_LIMIT_TYPE					"LimitType"


////////////////
//more 
////////////////

#define		ELEMENT_CARD_DATA				"CardData"
#define		ATT_INDEX_NUMBER				"CardData\\IndexNumber" 
#define		ELEMENT_TRANSACTIONS			"CardData\\Transaction"
#define		ELEMENT_TRANSACTION_ONLY		"Transaction"


#define		ATT_RECEIPT_EX					"Receipt\\ExtraInfo"
#define		ATT_FILER_2043					"Receipt\\ExtraInfo\\filer2043"		//4.0.128.280

#define		ATT_CHIP_CVM_LIST				"ChipCardExtraData\\CvmList"      //4.0.20.20
#define		ATT_CHIP_CVM_LIST_SIZE			"ChipCardExtraData\\CvmListSize"  //4.0.20.20


// 4.0.16.500
//Fuel configuration xml file 

// Main elements
#define		ELEMENT_CARWASH					"Carwash"
#define		ELEMENT_TAXES					"Taxes"
#define		ELEMENT_GRADES					"Grades"

//Define the attributes of car wash xml buffer (CW --> CarWash)
#define		SECTION_CARWASH_PROGRAMS		"Programs"
#define		SECTION_SINGLE_CARWASH_PROGRAM	"Program"

// Car wash program attributes
#define		ATT_CW_PROGRAM_ID				"Id"
#define		ATT_CW_PROGRAM_NAME				"Name"
#define		ATT_CW_PROGRAM_PRICE			"Price"
#define		ATT_CW_PROGRAM_PRODUCT_CODE		"ProductCode"

//4.0.20.501 - TD 65174:
//Main element:
#define     ELEMENT_TANKS                   "Tanks" 

//Tank attributes:
#define		ATT_TANK_NUMBER				"Number"
#define		ATT_TANK_REFERENCE			"Reference"
#define		ATT_TANK_LOCK_PUMPS			"LockConnectedPumps"

#endif

